language: node_js

env:
  - DB=postgres://postgres@localhost/travis_ci_test

node_js:
  - "stable"

services:
  -postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - node ./server/data/20170615125201-create-account.js -d postgres://postgres@localhost/travis_ci_test