language: node_js

env:
  - NODE_ENV="development"  

node_js:
  - "stable"

services:
  -postgresql

before_script:
  - "psql -c 'create database travis;' -U postgres"
  - "bundle exec sequelize db:migrate"