language: node_js

env:
  - NODE_ENV="development"
  - NODE_ENV="production";SESSION_SECRET="hello"

node_js:
  - "stable"

services:
  -postgresql

before_script:
  - psql -c 'create database postittestdb;' -U postgres