language: node_js

env:
  - NODE_ENV="development"
  - DATABASE_URL=$(curl http://api.postgression.com)  

node_js:
  - "stable"

services:
  -postgresql

before_script:
  - "psql -c 'create database travis;' -U postgres"